#!/bin/bash

user="$(whoami)"
tmpdir="/tmp/war_$user"
browser="x-www-browser"

function usage()
{
    echo "WAR file (KDE WEB archive) viewer in browser."
    echo
    echo "USAGE: $0 [options] file.war"
    echo "options:"
    echo "  -b 'str'    use browser (default = 'x-www-browser');"
    echo "  -h          help."
    echo
    exit 1
}
if [ $# = 0 ]
then
    usage
fi

browser="x-www-browser"

while getopts ":b:h" opt
do
    case $opt in
        b) browser="$OPTARG"
            ;;
        h) usage
            ;;
        *) echo "Unknown option -$OPTARG"
            exit 1
            ;;
    esac
done
shift "$(($OPTIND - 1))"
warfile="$1"
if [ -z "$warfile" ]
then
    usage
fi

rm -rf "$tmpdir"
mkdir -p "$tmpdir"
tar xz -C "$tmpdir" -f "$warfile"

$browser "$tmpdir/index.html"

rm -rf "$tmpdir"
