.TH war-bash 1 "21 Dec 2017" "0.20171221" "User Manual"
.SH NAME
war-browse
.SH DESCRIPTION
WAR file (KDE WEB archive) viewer in browser.
.SH USAGE
war-browse [options] file.war
.SH OPTIONS
.TP
\fB-b\fP 'str'
use browser (default = 'x-www-browser');
.TP
\fB-h\fP
display help and exit
.SH NAME
war-create
.SH DESCRIPTION
WAR file (KDE WEB archive) creator.
.SH USAGE
war-create [options] /path/to/html file.war
.SH OPTIONS
.TP
\fB-i\fP
using exist index.html.
.TP
\fB-h\fP
display help and exit
.SH COPYRIGHT
 Copyright (c) 2017 zvezdochiot
.SH SEE ALSO
 war-create(1).
.SH CONTACTS
 Homepage: https://github.com/zvezdochiot/war-bash
