#!/bin/bash

user="$(whoami)"
tmpdir="/tmp/war_$user"
tmpdirsed="\/tmp\/war_$user\/"

function usage()
{
    echo "WAR file (KDE WEB archive) creator."
    echo
    echo "USAGE: $0 [options] /path/to/html file.war"
    echo "options:"
    echo "  -i          using exist index.html."
    echo "  -h          help."
    echo
    exit 1
}
if [ $# = 0 ]
then
    usage
fi

indexuse="false"

while getopts ":ih" opt
do
    case $opt in
        i) indexuse="true"
            ;;
        h) usage
            ;;
        *) echo "Unknown option -$OPTARG"
            exit 1
            ;;
    esac
done
shift "$(($OPTIND - 1))"
htmldir="$1"
if [ ! -d "$htmldir" ]
then
    usage
fi
warfile="$2"
if [ -z "$warfile" ]
then
    warfile="$htmldir.war"
fi

if [ $indexuse = "true" ]
then
    if [ ! -f "$htmldir/index.html" ]
    then
        indexuse="false"
    fi
fi

rm -rf "$tmpdir"
mkdir -p "$tmpdir"
cp -frv "$htmldir" "$tmpdir"

if [ $indexuse = "true" ]
then
    tar cz -C "$tmpdir/$htmldir" -f "$warfile" .
else
    cat > "$tmpdir/index.html" <<EOF 
<!DOCTYPE html>
<!-- Source is http://www.warmplace.ru/ -->
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <title>$htmldir</title>
</head>
<body>
    <h1>$htmldir</h1>
    <ol>
EOF
    find "$tmpdir" -iname "*.html" | sed -e "s/$tmpdirsed//;s/.*/        <li><a href=\".\/&\">&<\/a><\/li>/;" >> "$tmpdir/index.html"
    find "$tmpdir" -iname "*.htm" | sed -e "s/$tmpdirsed//;s/.*/        <li><a href=\".\/&\">&<\/a><\/li>/;" >> "$tmpdir/index.html"
    cat >> "$tmpdir/index.html" <<EOF 
    </ol>
</body>
</html>
EOF
    sed -i -e '/<li><a href=".\/index.html">index.html<\/a><\/li>/d' "$tmpdir/index.html"
    tar cz -C "$tmpdir" -f "$warfile" .
fi
rm -rf "$tmpdir"
