.TH war-bash 1 "23 Dec 2017" "0.20171223" "User Manual"
.SH NAME
war-browse
.SH DESCRIPTION
WAR file (KDE WEB archive) viewer in browser.
.SH USAGE
war-browse [options] file.war
.SH OPTIONS
.TP
\fB-b\fP 'str'
use browser (default = 'x-www-browser');
.TP
\fB-h\fP
display help and exit
.SH NAME
war-create
.SH DESCRIPTION
WAR file (KDE WEB archive) creator.
.SH USAGE
war-create [options] /path/to/html/dir [file.war]
.SH OPTIONS
.TP
\fB-h\fP
display help and exit
.SH NAME
war-unpack
.SH DESCRIPTION
WAR file (KDE WEB archive) unpack.
.SH USAGE
war-unpack [options] file.war
.SH OPTIONS
.TP
\fB-h\fP
display help and exit
.SH NAME
war-wget
.SH DESCRIPTION
WAR file (KDE WEB archive) wget page.
.SH USAGE
war-wget [options] name url/to/html/page
.SH OPTIONS
.TP
\fB-c\fP
clean LIST (sample 'js,php,eot,wott,ttf', default = '')
.TP
\fB-r\fP
reject LIST (sample 'js,php,eot,wott,ttf', default = '')
.TP
\fB-h\fP
display help and exit
.SH CONFIG FILE
 /etc/war-bash.conf
 ~/config/war-bash.conf
.SH COPYRIGHT
 Copyright (c) 2017 zvezdochiot
.SH SEE ALSO
 war-create(1).
.SH CONTACTS
 Homepage: https://github.com/zvezdochiot/war-bash
